In [2]:
!pip3 install rasterio

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 3.8 MB/s eta 0:00:0000:0100:01
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/0b/f7/85273299ab57117850cc0a936c64151171fac4da49bc6fba0dad984a7c5f/affine-2.4.0-py3-none-any.whl (15 kB)


In [3]:
import geopandas as gpd
# 读取GeoJSON
geopath = '/Users/zgf/Downloads/同步空间/毕业设计/tools/test.geojson'
lindi = gpd.read_file(geopath)

In [10]:
import geopandas as gpd

# 读取GeoJSON
geopath = '/Users/zgf/Downloads/同步空间/毕业设计/tools/test.geojson'
lindi = gpd.read_file(geopath)

# 遍历每一个feature
for index, row in lindi.iterrows():
    # row['geometry'] 包含当前feature的几何信息
    geom = row['geometry']
    # 可以访问其他属性列，例如：
    # attr = row['some_attribute_column']
    print(geom.centroid)
    center = geom.centroid
    print(center.x, center.y)
    # 这里可以添加你的处理逻辑
    print("Feature ID:", index)
    print("Geometry:", geom)
    # 如果需要，可以继续处理几何对象geom和其他属性attr

POINT (112.093844909471 31.01556644197155)
112.093844909471 31.01556644197155
Feature ID: 0
Geometry: POLYGON ((112.093865 31.016215164, 112.09381163 31.0161826, 112.09369898 31.0160163, 112.09351122 31.01589292, 112.09336102 31.01580709, 112.093191216 31.015651074, 112.093078276 31.01550193, 112.093055656 31.015463986, 112.09309741 31.015442921, 112.093104844 31.01543917, 112.093115088 31.015434002, 112.093115519 31.015433785, 112.09311979 31.01543163, 112.093146073 31.01541837, 112.093167482 31.01540757, 112.093211304 31.015385461, 112.093453257 31.015263397, 112.093763398 31.015245046, 112.094098827 31.014970619, 112.094104119 31.014858254, 112.094104402 31.014852246, 112.094104657 31.014846823, 112.094105438 31.014830241, 112.094106841 31.014800453, 112.094181248 31.014781883, 112.094193265 31.014778884, 112.094194819 31.014782518, 112.094194956 31.014782839, 112.094195283 31.014783603, 112.094199888 31.01479118, 112.094200332 31.01479191, 112.094200568 31.014792299, 112.094223253 

In [4]:
import numpy as np
minx = 1.1
maxx = 3.4
scale = 0.5
x_values = np.linspace(minx, maxx, num=int((maxx - minx) / scale) + 1)
x_values

array([1.1  , 1.675, 2.25 , 2.825, 3.4  ])

In [2]:
from pyproj import Proj, transform

# 定义WGS 84坐标系（EPSG:4326）
wgs84 = Proj(init='epsg:4326')

# 定义Web Mercator坐标系（EPSG:3857）
web_mercator = Proj(init='epsg:3857')

# 经纬度坐标，例如：(纬度, 经度)
lat, lon = 23.0243, 105.9103,
  # 纽约市的经纬度

# 将WGS 84坐标转换为Web Mercator坐标
x, y = transform(wgs84, web_mercator, lon, lat)

print(f"Web Mercator Coordinates: ({x}, {y})")

Web Mercator Coordinates: (11789880.665762842, 2634957.5761673045)


/opt/homebrew/lib/python3.12/site-packages/pyproj/crs/crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
/opt/homebrew/lib/python3.12/site-packages/pyproj/crs/crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
/var/folders/d7/lvn7qn816xlcyc6zp72clg_h0000gn/T/ipykernel_38696/98145245.py:14: FutureWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
 

In [ ]:
            "GPS_X": 35471900,
            "GPS_Y": 2728138,

In [6]:
import numpy as np

# 生成从0到10的5个等间距样本
samples = np.linspace(117, 120, 4)
samples

array([117., 118., 119., 120.])

In [4]:
samples_exclusive

array([0., 2., 4., 6., 8.])